CREATE TABLE ACCOUNTS (
    ID UUID DEFAULT random_uuid() PRIMARY KEY,
    EMAIL VARCHAR(100),
    PASSWORD VARCHAR(50),
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    ACCOUNT_TYPE VARCHAR(50),
    VERSION INT
);
